version: '3'
services:
  order-service:
    build: './casan-order-service'
    ports:
      - "3001:3000"
    depends_on:
      - db
    environment:
      - MONGO_DB_URI=mongodb://db/myapp

  db:
    image: mongo
    ports:
      - "27017:27017"